import express from "express";
import { getUser, addUser, deleteUser, updateUser, lockUser, changeRole } from "../controllers/userController.js";
import { createComment, getCommentsByProduct, getCommentsGroupedByUser, deleteComment } from "../controllers/commentController.js";
import { createPromotion, getAllPromotions } from "../controllers/promotionsController.js";
import { verifyToken, requireAdmin } from "../middleware/authMiddleware.js";
import { uploadProduct, getProducts, getProductById, getProductsByCategory,deleteVariant, updateProduct, getBestSellingProducts, getDiscountedProducts, getCategory, searchProduct } from "../controllers/productController.js";
import { saveCart, getCart, removeItemFromCart } from "../controllers/cartController.js";
import { createPayment, vnpayReturn } from "../controllers/paymentController.js";
import { getOrdersByUserId, getOrdersGroupedByUser, updateOrderStatus } from "../controllers/orderController.js";
import verifyVnpayHash from "../middleware/vnpayVerify.js";
import upload from "./upload.js";
const router = express.Router();

router.get("/searchProducts", searchProduct);
router.get("/getProduct", getProducts);
router.get("/getProductById/:id", getProductById);
router.get("/getProductsByCategory", getProductsByCategory);
router.get("/getBestSellingProducts", getBestSellingProducts);
router.get ("/getCategory", getCategory);
router.post("/createPromotion" ,createPromotion);
router.get("/promotions", getAllPromotions);
router.get("/getDiscountedProducts", getDiscountedProducts);
router.post("/uploadProduct", upload.any(), uploadProduct);
router.delete('/products/:productId/rom/:rom/variant/:color', deleteVariant);
router.put("/updateProduct/:id", upload.any(), updateProduct);
router.get("/getUser", verifyToken, requireAdmin, getUser);
router.post("/addUser", addUser);
router.put("/toggleLockUser/:id", lockUser);
router.put("/toggleUserRole/:id", changeRole);
router.delete("/deleteUser/:id", deleteUser);
router.put("/updateUser/:id", updateUser);
router.post("/saveCart", verifyToken, saveCart);
router.get("/getCart", verifyToken, getCart);
router.put("/removeItemFromCart", verifyToken, removeItemFromCart);
router.post('/create-payment', createPayment);
router.get("/order/:vnp_TxnRef", verifyVnpayHash, vnpayReturn);
router.get("/getOdersByUserId/:userId", getOrdersByUserId);
router.patch("/admin/orders/:orderId/status", verifyToken, requireAdmin, updateOrderStatus);
router.get("/getOrdersGroupedByUser", verifyToken,requireAdmin, getOrdersGroupedByUser);
router.post("/createComment", verifyToken, createComment);
router.get("/getCommentByProduct/:id", getCommentsByProduct);
router.get("/comments/groupByUser", getCommentsGroupedByUser);
router.delete("/comments/:commentId", deleteComment);
export default router;
